# The character that needs to be inputted to trigger a command
bot_command_character: $
bot_version: "ONB Test Candidate 2.0.0"

server_id: "%"

permitted_command_channels: # What channels commands can be executed in
  - "1078426716940275773" # Commands
  - "1078426428598648943" # Raid Attendance

event_message_channels: # Channels where people post that they have gone live.
  - "1108661547355607052" # I Am Live

# The IDs of important channels
event_voice_channel: "1078426580013039697"
event_links_channel: "1078426613785575472"
who_i_supported_channel: "1078426297224671404"
calendar_support_channel: "1078426323875287040"
shout_out_support_channel: "1078426353755488328"
general_channel: "1078425644062474252"
logging_channel: "1078648010898165803"
request_a_slot_channel: "1078426697994612777"
rules_and_how_it_works_channel: "1078648010898165801"
event_info_channel: "1078426599361359932"
support_network_info_channel: "1078675591701733480"
who_invited_me_channel: "1078426378640302182"
report_channel: "1108662222978302004"

# 1 = Event, 2 = Initiation, 4 = Moderation, 8 = Calendar, 16 = Admin, 32 = Shoutout
# If someone has access to multiple categories, give them an access level equal to the numbers added together.
command_access_roles:
  - access_level: 63 # Admin Access
    id: "1078633422966235156" # Developer

  - access_level: 63 # Admin Access
    id: "1078633524606808075" # Admin


exempt_roles: # Roles that are exempt from checks
  - "1108662665619980342"

priority_event_roles:
  - "1108662564784701511"
on_leave_role: "1108662665619980342"

now_live_role: "1108662525836398612"
now_live_eligibility_role: "1078425642992934942"
super_featured_role: "1108666805800685669"
super_featured_live_role: "1108662564784701511"
new_member_role: "1108662720007524373"
event_exclusion_role: "1108662767902261269"

now_live_banned_roles:
  - "1108662665619980342"
  - "1108662767902261269"

minimum_points_required_per_week: 1
minimum_points_required_for_calendar: 25
minimum_calendar_tags_required_for_calendar: 2

server_account_discord_id: "%"
server_account_twitch_page_tag_multiplier: 2
featured_member_tag_multiplier: 2

maximum_calendar_tags: 10
calendar_clamp_type: "review" # "review", "database", "none"
calendar_max_slots: 18

points_awarded_for_activities:
  events: 5
  calendar_support: 1.5
  who_I_supported: 1
  shout_out_support: 1
  invited_support: 1

use_weekly_average: true
weeks_for_average: 4

# How many days should the database remember after the purge command has been executed
purge_date_limit: 60

# How many messages should catchup look through (the more, the slower it gets). Max of 100.
catchup_message_cap: 100

dm_for_failed_activity_check: false

time_between_message_history_save: 1